image: Ubuntu1804 # образ для сборки 
stack: node 16 # окружение 
branches: 
  only: 
    - master # ветка git 
# инструкции 
cache: node_modules # папка откуда берутся кешированные пакеты  
install: 
  - npm install # команда установки зависимостей 
build: off # не используется webpack 
test_script: 
  - npm run lint && npm test # скрипт сборки